# Generated by Django 6.0.4 on 2026-05-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchExclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitch_id', models.BigIntegerField(help_text="User's Twitch ID", unique=True)),
                ('optout_at', models.DateTimeField(auto_now_add=True, help_text='Time when the user requested the opt out.')),
            ],
        ),
    ]
