# Generated by Django 6.0.4 on 2026-07-31 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_accountsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the login happened (stored in UTC).')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Client IP the login came from.', null=True)),
                ('country_code', models.CharField(blank=True, help_text="ISO 3166-1 alpha-2 country code, e.g. 'DE'.", max_length=2)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(help_text='The user who logged in.', on_delete=django.db.models.deletion.CASCADE, related_name='login_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
