# Generated by Django 6.0.4 on 2026-05-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CachedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier for this cached page (e.g. 'home'). Used as the lookup key by the public API.", max_length=64, unique=True)),
                ('content', models.JSONField(help_text='Pre-rendered page payload returned to the frontend as-is.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time of the latest cache refresh for this page.')),
            ],
        ),
    ]
