# Generated by Django 6.0.4 on 2026-05-21 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0006_stream_genre_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(help_text='Deterministic hash of the normalized filter set. Two requests representing the same search share one row.', max_length=64, unique=True)),
                ('filters', models.JSONField(help_text='Normalized filter values that produced this entry. Kept for debugging/inspection; not used for lookup (key_hash is).')),
                ('results', models.JSONField(help_text='Cached search payload returned to the frontend as-is.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this entry was first computed.')),
                ('refreshed_at', models.DateTimeField(auto_now=True, help_text='Time of the latest recompute for this entry. TTL freshness is evaluated against this value.')),
                ('last_hit_at', models.DateTimeField(auto_now_add=True, help_text='Updated every time the entry is read. Used by eviction to drop entries no one queries anymore.')),
            ],
        ),
    ]
