# Generated by Django 6.0.4 on 2026-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0007_search_cache'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier for this cache entry (e.g. 'streamers_distribution'). Used as the lookup key by readers.", max_length=64, unique=True)),
                ('content', models.JSONField(help_text='Cached JSON payload returned to callers as-is.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time of the latest cache refresh for this entry. TTL freshness is evaluated against this value.')),
            ],
        ),
    ]
