# Generated by Django 6.0.4 on 2026-05-24 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0008_jsoncache'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamerProfileCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField(help_text='Cached profile payload (e.g. list of streams) returned to callers as-is.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this entry was first computed.')),
                ('refreshed_at', models.DateTimeField(auto_now=True, help_text='Time of the latest recompute for this entry. TTL freshness is evaluated against this value.')),
                ('last_hit_at', models.DateTimeField(auto_now_add=True, help_text='Updated every time the entry is read. Used by eviction to drop entries no one queries anymore.')),
                ('streamer_profile', models.OneToOneField(help_text='Streamer whose profile payload this row caches.', on_delete=django.db.models.deletion.CASCADE, related_name='profile_cache', to='streams.streamerprofile')),
            ],
        ),
    ]
