# Generated by Django 6.0.4 on 2026-06-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0010_stream_avg_viewers'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(condition=models.Q(('status', 'approved')), fields=['language', 'finished_at'], name='stream_approved_search_idx'),
        ),
    ]
