# Generated by Django 6.0.4 on 2026-06-03 15:03

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0011_stream_stream_approved_search_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchStatsRebuildState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_profile_id', models.BigIntegerField(default=0, help_text='Highest StreamerProfile.id processed by the last rebuild chunk.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StreamerSearchStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='ISO 639-1 language code; one row per (streamer, language) pair.', max_length=2)),
                ('peak_viewers', models.PositiveIntegerField(help_text="Max peak viewers across the streamer's approved streams in the last 4 weeks.")),
                ('avg_viewers', models.PositiveIntegerField(help_text='Mean of per-stream avg viewers over the same streams, rounded.')),
                ('total_duration_seconds', models.PositiveIntegerField(help_text="Total streamed seconds over the same streams; shown as 'X hours in last 4 weeks'.")),
                ('streams_count', models.PositiveIntegerField(help_text='Number of approved streams contributing to this row.')),
                ('genre_ids', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, default=list, help_text='Distinct GameGenre.host_genre_id values played in the window; filtered by overlap.')),
                ('host_login', models.CharField(max_length=64)),
                ('host_display_name', models.CharField(max_length=255)),
                ('computed_at', models.DateTimeField(auto_now=True, help_text='When this row was last recomputed.')),
                ('streamer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_stats', to='streams.streamerprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['language', '-peak_viewers', '-avg_viewers'], name='searchstats_lang_peak_idx'), models.Index(fields=['language', '-avg_viewers'], name='searchstats_lang_avg_idx'), models.Index(fields=['language', '-total_duration_seconds'], name='searchstats_lang_dur_idx'), django.contrib.postgres.indexes.GinIndex(fields=['genre_ids'], name='searchstats_genre_ids_gin')],
                'constraints': [models.UniqueConstraint(fields=('streamer_profile', 'language'), name='unique_streamer_language_stats')],
            },
        ),
    ]
