# Generated by Django 6.0.4 on 2026-06-04 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0012_searchstatsrebuildstate_streamersearchstats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchCache',
        ),
        migrations.RemoveIndex(
            model_name='stream',
            name='stream_approved_search_idx',
        ),
    ]
