# Generated by Django 6.0.4 on 2026-06-10 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streams', '0013_delete_searchcache_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreStatsBuildState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_profile_id', models.BigIntegerField(default=0, help_text='Highest StreamerProfile.id processed by the last rebuild chunk.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streams_count', models.PositiveBigIntegerField(default=0, help_text='Approved streams in the last 4 weeks that played at least one game of this genre. A stream spanning several genres counts once toward each.')),
                ('streamers_count', models.PositiveBigIntegerField(default=0, help_text='Distinct streamers with at least one such stream in the window.')),
                ('total_duration_seconds', models.PositiveBigIntegerField(default=0, help_text="Genre's share of streamed seconds in the window, split per stream by the fraction of snapshots on this genre's games. Non-game time (e.g. Just Chatting) is excluded.")),
                ('computed_at', models.DateTimeField(blank=True, help_text='When the published values were last swapped in (end of a full build cycle).', null=True)),
                ('draft_streams_count', models.PositiveBigIntegerField(default=0)),
                ('draft_streamers_count', models.PositiveBigIntegerField(default=0)),
                ('draft_total_duration_seconds', models.PositiveBigIntegerField(default=0)),
                ('genre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='streams.gamegenre')),
            ],
        ),
    ]
